### PR TITLE
Readme.md

### PR DESCRIPTION
**Pull request by sepakauyang40kali**
Able to readme.md

### CODE REVIEW

**Comment by sepakauyang40kali** [comment]
pushing to the [patch-4](https://github.com/sepakauyang40kali/its-a-unix-gallery/tree/patch-4) branch on [sepakauyang40kali/its-a-unix-gallery](https://github.com/sepakauyang40kali/its-a-unix-gallery).

**Comment by sepakauyang40kali** [comment]
sepakauyang40kali:patch-4

**Comment by sepakauyang40kali** [comment]
#1 [Googlephoto.com](amalina9507@gmail.com)

**Comment by bhm** [comment]
I have one question.

Why?

**Review by sepakauyang40kali — COMMENTED** [review]
Approve

**Comment by bhm** [comment]
I am not adding some random email to a readme.

**Pull request closed without merging**
